# Generated by Django 3.0.6 on 2020-10-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_user_islogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isLogin',
            field=models.BooleanField(default=False),
        ),
    ]
