# Generated by Django 3.0.6 on 2020-10-20 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_auto_20201019_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
                ('password', models.CharField(default=None, max_length=50)),
                ('host', models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000'))),
                ('members', models.TextField(default='[]')),
            ],
        ),
    ]
