# Generated by Django 3.0.6 on 2020-10-20 05:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
