# Generated by Django 3.0.6 on 2020-10-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0008_user_lastlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='chats',
            field=models.TextField(default='[]'),
        ),
    ]
