# Generated by Django 3.0.6 on 2020-10-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_room_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
