# Generated by Django 3.0.6 on 2020-11-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0010_auto_20201031_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(default='', max_length=60, primary_key=True, serialize=False)),
                ('wolf_choices', models.TextField(default='[]')),
                ('witch_choice', models.CharField(default='', max_length=60)),
                ('prophet_choice', models.CharField(default='', max_length=60)),
                ('hunter_choice', models.CharField(default='', max_length=60)),
                ('witchPoison', models.IntegerField(default=1)),
                ('witchAntidote', models.IntegerField(default=1)),
            ],
        ),
    ]
