# Generated by Django 3.0.6 on 2020-11-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0011_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='wolf_choices',
            field=models.TextField(default='{}'),
        ),
    ]
